### ISSUE TITLE
Question: how to configure app server

### ISSUE THREAD

**Issue by mehdisadeghi** [hiposfer/hive#19]
`react-native run-android` successfully builds and installs the app on my Nexus 5, however the app tries to connect to localhost server. Where can I change this?

**Comment by carocad** [comment]
@mehdisadeghi are you connecting through USB cable? If not I wouldnt know what to tell you because I always run it with usb cable.

If you are talking about the message: "fetching JS bundle" or the one "loading files from figwheel" then you need to configure `adb` to forwards the ports used by figwheel and by the repl so that they can all communicate.

See https://github.com/drapanjanas/re-natal#using-real-android-device for more information

**Comment by carocad** [comment]
By the way, the current project configuration only works if you connect figwheel to Cursive. If you start them from the terminal I think funny things can happen. That is still a problem to solve. For now I use Cursive for everything so it was not a priority ;)

**Comment by mehdisadeghi** [comment]
Yes I use USB cable so we can share the same experience :) And good to know about adb port-forwardning! I'll try that. For Cursive part I have not used it yet, I heavily use SublimeText, so I configured it for Closure and so far I am happy! :)

**Comment by carocad** [comment]
@mehdisadeghi unfortunately I cannot help you much with Sublime since I have never used.

What I can tell you is this: Currently figwheel is configured to run as a library not as an application. You can change that by uncommenting the line in `project.clj` about the figwheel plugin. That should let you run it directly from the command line as: `lein figwheel android`.

Once it is running you should check how to make a remote connection to your repl, i.e. a so called nrepl connection. Usually when figwheel starts it tells you on which port it is running. You would need to setup a connection between sublime and figwheel.

I hope it helps

**Comment by carocad** [comment]
maybe this helps: http://code.haleby.se/2017/02/24/connect-cursive-to-figwheel-repl/

**Comment by carocad** [comment]
@mehdisadeghi I am closing this since last time that we did pair programming it worked for you and now we use expo instead of react native directly.
