### ISSUE TITLE
create no-internet error screen

### ISSUE THREAD

**Issue by carocad** [hiposfer/hive#88]
We had this before but removed it due to the use of Native Base.

@mehdisadeghi I think this would be a good issue for you as it involves all parts of the app i.e.
- set up a react native connection listener
- transact it in the database
- check for errors on http request
- dispatch a screen change

What do you think?

**Comment by carocad** [comment]
![missinginternet](https://user-images.githubusercontent.com/10408729/41193712-7812e560-6c10-11e8-9528-adc67efdc7bf.png)

**Comment by carocad** [comment]
> However I didn't realize that it was because of Native Base.

Native base was the excuse that I used to remove it 😄 . Actually I just didnt have the time to introduce it again after so many breaking changes so it just got abandoned ...

**Comment by mehdisadeghi** [comment]
Has the top level connection error message solved this? Should we close this and have another issue for unhandled promise failures?

I looked at many similar apps and played alot with hive and at the end I realized there is no one-size-fits-all solution for failed network request errors. I think each component should handle its own (promise) failures, which would be a big problem.

What got me thinking was a solution to be able to _retry_ the failed operation, i.e. having a retry button on a component which reports failure. In certain cases user can simply repeat the task, however sometimes it is not possible. For example imaging the direction page has multiple tabs for driving, walking, etc., and we load each tab upon navigation. In this case a retry button is almost necessary, since the user can't go back and repeat the direction request.

@carocad what do you think?

**Comment by carocad** [comment]
Yeah I think we should close this. 

The main purpose of the ticket is done.

We could probably improve it but that applies to every issue here

As for the retry button, I think that this would definitely come but I wouldn't try to do that now as we barely have any operations in hive.

The only one that could fail is the directions request which is trivial to retry.

I think we should wait a bit and see how our operations evolve and create a concept based on that

**Comment by mehdisadeghi** [comment]
I agree. Closing.
